repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-json
        -   id: check-added-large-files
        -   id: no-commit-to-branch
            args: [--branch, main]
        -   id: check-merge-conflict

  -   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
      rev: v2.12.0
      hooks:
        -   id: pretty-format-java
            args: [--autofix]

  -   repo: https://github.com/gherynos/pre-commit-java
      rev: v0.2.4
      hooks:
        -   id: checkstyle
            args: ['-c', 'google_checks.xml']
        -   id: pmd
        -   id: spotbugs
            args: ['-effort', 'max']